### ISSUE TITLE
Is it possible to apply to segmentation task using mask rcnn as task model?

### ISSUE THREAD

**Issue by benlee73** [joffery/M-ADA#10]
I would like to apply single domain generalization to a segmentation problem.

So, is it possible to use this method and code? And is it effective?

I would be very grateful if you could reply.

**Comment by joffery** [comment]
Hi @benlee73,

It is a good point! 
Our method should be model agnostic, but I haven't tried other segmentation models.
One potential concern is that the strength for adversarial perturbation (learning rate and iterations) should be adjusted accordingly. 

Best,
Fengchun
