### ISSUE TITLE
About the relaxation loss in code & paper

### ISSUE THREAD

**Issue by ThomasMrY** [joffery/M-ADA#2]
Hi, I find there is a small typo in your code(or maybe in the paper):
In your paper the relaxation loss is define as follows:
![image](https://user-images.githubusercontent.com/26043876/86596625-1f25e700-bfcd-11ea-936f-2ddabc3f0a46.png)
However, in your code, this loss is computed as:
![image](https://user-images.githubusercontent.com/26043876/86596943-9e1b1f80-bfcd-11ea-8b31-05cdfc304039.png)
I wonder which one is true here.
BTW, can you share me some of the images that WAE generated in different domains, I am really curious about it?
Thanks.

**Comment by joffery** [comment]
Hi @ThomasMrY ,

Thanks for your interest in our work! 
Please refer to Sec. B.2 in the supplementary for more details about the implementation of the relaxation term.

Best,
Fengchun

**Comment by ThomasMrY** [comment]
Hi, Fengchun
Thanks for your respounse.
Sec. B.2 seems dosen't dispel my conserns: "The relex loss in the paper is not consistent with the loss in the code". 
If I understand correctly, I think the loss defined in the paper should be implemented as: "mse_loss(input_aug,recon_batch_aug)"
If I have any misunderstandings, please help me to point them out.
Thanks,
Tao

**Comment by joffery** [comment]
Hi Tao,

Eq.(7) is the straightforward way to implement the relaxation term. However, in practice, it is hard to train an ideal
WAE achieving x≈V(x). As a result, there may exist inconsistency between the input space and the reconstruction space, which is the reason why "mse_loss(recon_batch ,recon_batch_aug)" is the practical implementation.

Thanks,
Fengchun

**Comment by ThomasMrY** [comment]
Thanks, Understand!

**Comment by llzygg** [comment]
> Thanks, Understand!

您好，我看完你们的交流后还是不太理解，能帮忙再讲解一下吗？谢谢

**Comment by ThomasMrY** [comment]
hi，你好，

可以加我的微信 yt_thomas_Y

祝好



-----原始邮件-----
发件人:llzygg ***@***.***>
发送时间:2025-01-03 21:32:45 (星期五)
收件人: joffery/M-ADA ***@***.***>
抄送: "Tao Yang" ***@***.***>, "State change" ***@***.***>
主题: Re: [joffery/M-ADA] About the relaxation loss in code & paper (#2)






Thanks, Understand!

您好，我看完你们的交流后还是不太理解，能帮忙再讲解一下吗？谢谢
