### ISSUE TITLE
Inconsistency in the constraint loss in the code & paper

### ISSUE THREAD

**Issue by tkong1998** [joffery/M-ADA#4]
Hi,

Thanks for releasing the code!

However, I found an inconsistency in the constraint loss mentioned in the paper and in implementation. In the paper, I believe, it is <img width="423" alt="image" src="https://user-images.githubusercontent.com/43145618/98270624-04d73680-1fca-11eb-9ed0-84bc579af418.png">, while in the code, it is only the mse between the z and z+. I wonder where the infinity part goes.

Thank you so much!

**Comment by joffery** [comment]
Hi @tkong1998，

Thanks for your interest in our work! 
Eq.5 indicates that augmentation should keep the label unchanged.
The formulation and implementation is the same as [56].

Best,
Fengchun

**Comment by tkong1998** [comment]
Hi Fengchun,

Thanks for your response!

Best,
Monique
